@API_HostAddress = http://localhost:5291

GET {{API_HostAddress}}/photos/summarise/{{ollamaModel}}
Accept: application/json

###
GET {{API_HostAddress}}/photos/summarise/{{florenceModel}}
Accept: application/json

###

GET {{API_HostAddress}}/api/photos/index/test-photos
Accept: application/json

###

GET {{Nominatim_HostAddress}}/reverse?format=geojson&namedetails=1&lat=51.503&lon=0.003338

###

GET {{Nominatim_HostAddress}}/status?format=json

###

GET {{Nominatim_HostAddress}}/search?q=park



###

GET {{API_HostAddress}}/api/photos
Accept: application/json

###
 

