@PhotoSearch.API_HostAddress = http://localhost:5291

GET {{PhotoSearch.API_HostAddress}}/photos/summarise/llava:7b
Accept: application/json

###

GET {{PhotoSearch.API_HostAddress}}/photos/index/test-photos
Accept: application/json

###
