/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
import { PhotoSummary } from "./models/PhotoSummary";
export { MatchResults } from "@stencil-community/router";
export { PhotoSummary } from "./models/PhotoSummary";
export namespace Components {
    interface AppHome {
    }
    interface AppPhotos {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface MapComponent {
    }
    interface PhotoSummaryView {
        "availableModels": Set<string>;
        "categories": Array<string>;
        "objects": Array<string>;
        "selectedModel": string;
        "selectedPhoto": PhotoSummary;
        "selectedSummary": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppPhotosElement extends Components.AppPhotos, HTMLStencilElement {
    }
    var HTMLAppPhotosElement: {
        prototype: HTMLAppPhotosElement;
        new (): HTMLAppPhotosElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLMapComponentElement extends Components.MapComponent, HTMLStencilElement {
    }
    var HTMLMapComponentElement: {
        prototype: HTMLMapComponentElement;
        new (): HTMLMapComponentElement;
    };
    interface HTMLPhotoSummaryViewElement extends Components.PhotoSummaryView, HTMLStencilElement {
    }
    var HTMLPhotoSummaryViewElement: {
        prototype: HTMLPhotoSummaryViewElement;
        new (): HTMLPhotoSummaryViewElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-photos": HTMLAppPhotosElement;
        "app-root": HTMLAppRootElement;
        "map-component": HTMLMapComponentElement;
        "photo-summary-view": HTMLPhotoSummaryViewElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppPhotos {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface MapComponent {
    }
    interface PhotoSummaryView {
        "availableModels"?: Set<string>;
        "categories"?: Array<string>;
        "objects"?: Array<string>;
        "selectedModel"?: string;
        "selectedPhoto"?: PhotoSummary;
        "selectedSummary"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-photos": AppPhotos;
        "app-root": AppRoot;
        "map-component": MapComponent;
        "photo-summary-view": PhotoSummaryView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-photos": LocalJSX.AppPhotos & JSXBase.HTMLAttributes<HTMLAppPhotosElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "map-component": LocalJSX.MapComponent & JSXBase.HTMLAttributes<HTMLMapComponentElement>;
            "photo-summary-view": LocalJSX.PhotoSummaryView & JSXBase.HTMLAttributes<HTMLPhotoSummaryViewElement>;
        }
    }
}
